# Generated by Django 4.1.5 on 2023-02-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('updated_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default=' ')),
                ('updated_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
